### ISSUE TITLE
Importar y exportar presets con funciones de transferencia

### ISSUE THREAD

**Issue by fblupi** [fblupi/grado_informatica-TFG#19]
Para ello hacer uso de XML.

Hacer uso de una librería que facilite el trabajo con este tipo de archivos. Para ello, buscar la más adecuada.

Un ejemplo podría ser:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<tf name="CT-WoodSculpture" description="Escultura de madera con clavos y una capa de estuco y policromado">
    <color>
        <point>
            <x>-750</x>
            <r>0.08</r>
            <g>0.05</g>
            <b>0.03</b>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-350</x>
            <r>0.39</r>
            <g>0.25</g>
            <b>0.16</b>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-200</x>
            <r>0.8</r>
            <g>0.8</g>
            <b>0.8</b>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>3000</x>
            <r>0.5</r>
            <g>0.5</g>
            <b>0.5</b>
            <m>0.5</m>
            <s>0.0</s>
        </point>
    </color>
    <scalar>
        <point>
            <x>-800</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-750</x>
            <y>1</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-350</x>
            <y>1</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-300</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-200</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>-100</x>
            <y>1</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>1000</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>2750</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>2976</x>
            <y>1</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>3000</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
    </scalar>
    <gradient>
        <point>
            <x>0</x>
            <y>0</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>350</x>
            <y>0.2</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
        <point>
            <x>2000</x>
            <y>1</y>
            <m>0.5</m>
            <s>0.0</s>
        </point>
    </gradient>
</tf>
```

**Comment by romanarranz** [comment]
Para ver que **requisitos** tienes exactamente mira el diagrama de flujo de este enlace: [Diagrama de Flujo](http://stackoverflow.com/questions/9387610/what-xml-parser-should-i-use-in-c)

Una de las mejores opciones que se presentan es [RapidXML](http://rapidxml.sourceforge.net) porque:
- Ofrece una velocidad de parseo para una cantidad de N datos semejante a la función strlen (incluyendo la generación del DOM).
- Parsea aproximadamente 1 billón de caracteres por segundo.
- Buena gestión de la memoria en cuanto a la creación del DOM (árbol de etiquetas).
- La integración corre a cuenta de las inclusión de cabeceras.
- Licencia propietaria y libre.
- Soporta las codificaciones UTF-8, UTF-16 de forma parcial y UTF-32.
- No tiene dependencias de librerías de terceros.

O bien puedes usar el conjunto de librerías que ofrece [Boost](http://www.boost.org) en las cuales podrás encontrar una para XML en los siguientes enlaces:
- [Boost XML Parser](http://www.boost.org/doc/libs/1_55_0/doc/html/boost_propertytree/parsers.html)
- [Tutorial 5 min parse XML](http://www.boost.org/doc/libs/1_42_0/doc/html/boost_propertytree/tutorial.html)
- [Tutorial extenso XML Parser Boost](https://akrzemi1.wordpress.com/2011/07/13/parsing-xml-with-boost/)

_Boost hace uso de RapidXML_

**Comment by fblupi** [comment]
Muchas gracias por el aporte.

He decidido finalmente hacerlo con las librerías de Boost. Si no fuese por ti aún estaría compilando librerías mucho más complejas para nada.
